{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms.watchdogessentials",
    "module": "watchdogessentials",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "watchdogessentials-1.0.0.jar",
          "url": "watchdogessentials-1.0.0.jar",
          "size": 160728,
          "sha512": "44075f162774a5150d3fae830df514fe37bb55922237b4832d10d807108e9a1633324f9f59dbebaad83585133375ba8b2a86c0a925e664472a4f0446c99ac01f",
          "sha256": "5b7d9e9b20489295e2c114f0d367caf8b86ba16bf02071e78b56e679f8e5dca0",
          "sha1": "4b469d1d1b8422d843c3370cd962c709ef14f895",
          "md5": "b74ff607e857eaf5c27ce4e7ed887a9f"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "watchdogessentials-1.0.0.jar",
          "url": "watchdogessentials-1.0.0.jar",
          "size": 160728,
          "sha512": "44075f162774a5150d3fae830df514fe37bb55922237b4832d10d807108e9a1633324f9f59dbebaad83585133375ba8b2a86c0a925e664472a4f0446c99ac01f",
          "sha256": "5b7d9e9b20489295e2c114f0d367caf8b86ba16bf02071e78b56e679f8e5dca0",
          "sha1": "4b469d1d1b8422d843c3370cd962c709ef14f895",
          "md5": "b74ff607e857eaf5c27ce4e7ed887a9f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "watchdogessentials-1.0.0-sources.jar",
          "url": "watchdogessentials-1.0.0-sources.jar",
          "size": 8310,
          "sha512": "7153273915d294c0255dc80d7f8aa1adabbd7daaefa2193c831eaf091e64f083bd3d3dd37d50a08af293471a2e4ccc98a2c9993ea0d8d61c63189fdbe9da7364",
          "sha256": "7f5d3aa9d72fc29b6c4c06dcfaa6e476e5131f0e9440d7c54ee9081a383933fd",
          "sha1": "f145540af3f41d815bdb7dc7f4375b13d286adc0",
          "md5": "32029315ee1a9403f972292815c649ef"
        }
      ]
    }
  ]
}
