{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms.watchdogessentials",
    "module": "watchdogessentials",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "watchdogessentials-1.0.0.jar",
          "url": "watchdogessentials-1.0.0.jar",
          "size": 527564,
          "sha512": "033ab91ead2909bc3bcb981d04e9f87834e7f6325883538ac853428b92a07028d62e446e879d870b6e8905e7f1a23c815778d2d24ca7deee42fb9c24d89764b0",
          "sha256": "ad57581592f79183d9fb955c50f5d410f45a749360517d3ff3e95988b30eaa1c",
          "sha1": "42826a566b8a6842c3584c74d987eeea96d66d48",
          "md5": "f762a471d89184c9390e5c02a34272df"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "watchdogessentials-1.0.0.jar",
          "url": "watchdogessentials-1.0.0.jar",
          "size": 527564,
          "sha512": "033ab91ead2909bc3bcb981d04e9f87834e7f6325883538ac853428b92a07028d62e446e879d870b6e8905e7f1a23c815778d2d24ca7deee42fb9c24d89764b0",
          "sha256": "ad57581592f79183d9fb955c50f5d410f45a749360517d3ff3e95988b30eaa1c",
          "sha1": "42826a566b8a6842c3584c74d987eeea96d66d48",
          "md5": "f762a471d89184c9390e5c02a34272df"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "watchdogessentials-1.0.0-sources.jar",
          "url": "watchdogessentials-1.0.0-sources.jar",
          "size": 375147,
          "sha512": "65e279f80c2682f96dd1932293396fb6eb82dceb3ae44976e87fd090083411275c476afd620204580f923f0e2617dbcf07f06b029fd71507ded3460fa08057f4",
          "sha256": "9d90703138824dcc27065f6f8548232538b79d6ceac647d1aa93926c9f98f863",
          "sha1": "42389176bc340f89dfa958cc5d0bfbe1e819b638",
          "md5": "8d98573616e631d5ba2bdd95be2e7cfc"
        }
      ]
    }
  ]
}
