{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms",
    "module": "oms",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-1.0.0.jar",
          "url": "oms-1.0.0.jar",
          "size": 211938,
          "sha512": "03b58687b8ac1d26887b73a801e00b5326fdd1357157fbd22a94a4d9904cef1a5ac42d082b650e5252890c8a2df6ada26e55014f2f6b869f32e4d4aed7888b8c",
          "sha256": "d72bb28433ddca540f7b19c6dcecfdfe5c1e1170829da83bae2cd216724b789b",
          "sha1": "af904cabfc5afc424140b4d524bbd9378c46d8b3",
          "md5": "54c1edb64a6f5e676fa3c1d0cbc7bec4"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-1.0.0.jar",
          "url": "oms-1.0.0.jar",
          "size": 211938,
          "sha512": "03b58687b8ac1d26887b73a801e00b5326fdd1357157fbd22a94a4d9904cef1a5ac42d082b650e5252890c8a2df6ada26e55014f2f6b869f32e4d4aed7888b8c",
          "sha256": "d72bb28433ddca540f7b19c6dcecfdfe5c1e1170829da83bae2cd216724b789b",
          "sha1": "af904cabfc5afc424140b4d524bbd9378c46d8b3",
          "md5": "54c1edb64a6f5e676fa3c1d0cbc7bec4"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oms-1.0.0-sources.jar",
          "url": "oms-1.0.0-sources.jar",
          "size": 24866,
          "sha512": "80a0e5a2089429119fff1feed068f659585653939a44dbb16ec7d2f140dbc93f0079d590a40a7e70efa2fb3c3933262b6e94a47b07cf47facc5f202206380f76",
          "sha256": "773fafe46aea398b1b4786f7737ac81ac455796dbd16fedb93e7c7db5f486a34",
          "sha1": "b80a04982767ec664cca70946bbdf31c8f2e2c7b",
          "md5": "021aa2197731024a9fb29415fc6c3230"
        }
      ]
    }
  ]
}
