{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms",
    "module": "oms",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-1.0.0.jar",
          "url": "oms-1.0.0.jar",
          "size": 228675,
          "sha512": "a5dbecd6a2e0dd90436cb39252ed1ddce30f4289ea96a4bc0108d6adaa894dd0b4ed4471057f98218ddfc9fc653d073af8878f800fb827078c8d12c2da74168f",
          "sha256": "455055abd6f586b1561bf442d7ecea4c813c829ff72b94eeeb24ddda1a9cc36a",
          "sha1": "74b876174401f1e6a9089785187c047ffacff78c",
          "md5": "bd63b6e2846a03b1360f18aec29ab266"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-1.0.0.jar",
          "url": "oms-1.0.0.jar",
          "size": 228675,
          "sha512": "a5dbecd6a2e0dd90436cb39252ed1ddce30f4289ea96a4bc0108d6adaa894dd0b4ed4471057f98218ddfc9fc653d073af8878f800fb827078c8d12c2da74168f",
          "sha256": "455055abd6f586b1561bf442d7ecea4c813c829ff72b94eeeb24ddda1a9cc36a",
          "sha1": "74b876174401f1e6a9089785187c047ffacff78c",
          "md5": "bd63b6e2846a03b1360f18aec29ab266"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oms-1.0.0-sources.jar",
          "url": "oms-1.0.0-sources.jar",
          "size": 27934,
          "sha512": "c3aed1d5d60110f6645cf29d86395fefceff9e1ccf8d7ae36fa6e93e733ee2b81da9f605237ed17176aa6b54f6a6007dd4d708d7c43da33ff37d5ee8c29831b4",
          "sha256": "d0de4e147a162accdf0082f7d1e9108d1b1446ca3e6b7431d387e7dc532b4f31",
          "sha1": "ea878083680b8bcceadf60bf33ee5097400692a7",
          "md5": "2cdc9bd703815451a7a060b1f7e8c4ae"
        }
      ]
    }
  ]
}
