{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms",
    "module": "oms",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-1.0.0.jar",
          "url": "oms-1.0.0.jar",
          "size": 211928,
          "sha512": "8381d174ce778dec5b46fbd22e641aca7f73d5745b5207d62f2e5622e410330313ecaf9197301fc2f42b31aa68336150b6fbccec2335e6222df90feb34be5de1",
          "sha256": "4f2e0d1c243fce5a0e6edb32526b0475765f2b14051fafef7b4c1158852be490",
          "sha1": "59405e88900c650715e45b32efed2504a8a09689",
          "md5": "f5afbf44b871f34cc4b2cca96991a76b"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-1.0.0.jar",
          "url": "oms-1.0.0.jar",
          "size": 211928,
          "sha512": "8381d174ce778dec5b46fbd22e641aca7f73d5745b5207d62f2e5622e410330313ecaf9197301fc2f42b31aa68336150b6fbccec2335e6222df90feb34be5de1",
          "sha256": "4f2e0d1c243fce5a0e6edb32526b0475765f2b14051fafef7b4c1158852be490",
          "sha1": "59405e88900c650715e45b32efed2504a8a09689",
          "md5": "f5afbf44b871f34cc4b2cca96991a76b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oms-1.0.0-sources.jar",
          "url": "oms-1.0.0-sources.jar",
          "size": 24853,
          "sha512": "c57f3d083259d41f9c0c955c1ef6d7704bbc9cc1dc0f5c7c1aef8e0c91305cbfd42c94c83969f066bf751b9e799e47b718e92d40e31e4fde1021fb4b256572b4",
          "sha256": "63acee32b73ae3fa034f39fceacb62327e882f806acbde35a954aab4ee50d9bf",
          "sha1": "40c32ae1e52db253ea7c3ce97fb54357f59528f0",
          "md5": "172798f912cb458bb0b81a621f518b2e"
        }
      ]
    }
  ]
}
