{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms",
    "module": "oms-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-api-1.0.0.jar",
          "url": "oms-api-1.0.0.jar",
          "size": 48179,
          "sha512": "e34acc3461246dbd521750c4902b7bd2c0d7cb2303738dbb988b0d05bb9c0a62337692da54674b6af017f05a0fd0bbc251221847a17af4b61f2c57f0ea077587",
          "sha256": "a4cc1fe970eec9b7f20e6f60035be4b1544dcab2401155f5d7ee6ffe152ec0d7",
          "sha1": "7b551f2dd9a4ce8832983390385be6b1ac24c344",
          "md5": "08c250167c40b25fdb39550dd575b27c"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-api-1.0.0.jar",
          "url": "oms-api-1.0.0.jar",
          "size": 48179,
          "sha512": "e34acc3461246dbd521750c4902b7bd2c0d7cb2303738dbb988b0d05bb9c0a62337692da54674b6af017f05a0fd0bbc251221847a17af4b61f2c57f0ea077587",
          "sha256": "a4cc1fe970eec9b7f20e6f60035be4b1544dcab2401155f5d7ee6ffe152ec0d7",
          "sha1": "7b551f2dd9a4ce8832983390385be6b1ac24c344",
          "md5": "08c250167c40b25fdb39550dd575b27c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oms-api-1.0.0-sources.jar",
          "url": "oms-api-1.0.0-sources.jar",
          "size": 11356,
          "sha512": "b06a6f025e69c8196be24309bf2731b495935018d1641d96ebe511ea287dddbbb9f9721dbb4d81a38df784e0fdbe7318ea934aba6e1dc822db6cf90f0a2176ad",
          "sha256": "83d9e11674c6131dd6130aff0969bea10096bf1f7ef07189635298da4d1216f6",
          "sha1": "6b385c472429841ee685f200b9ff1e3d7c09370e",
          "md5": "5c56cf6c031714edc20cb5f776dfad8c"
        }
      ]
    }
  ]
}
