modLoader = "kotlinforforge"
loaderVersion = "[${forge_version},)"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_display_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "icon.png"


[[dependencies.${ mod_id }]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "SERVER"

[[dependencies.${ mod_id }]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version}"
ordering = "NONE"
side = "SERVER"

[[dependencies.${ mod_id }]]
modId = "oms"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "SERVER"