{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms",
    "module": "oms-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-api-1.0.0.jar",
          "url": "oms-api-1.0.0.jar",
          "size": 59334,
          "sha512": "5dc5452e667b1ca1117dfb867404a0f6ac3fbb5dcf582d00929d2ea899dd450fb08497d6a857089b1b6562ff372ba3688dff8e495a730634271cef4fc981cdc7",
          "sha256": "a17d141e3cc6e7dd8a2dd886f3d83f413b21bdc2703af16c5ccbf790d6270951",
          "sha1": "941b758c6562cff36b2222ec7f3e3a9aa2ea0ea3",
          "md5": "4075533830c909610d741e3d491e99ba"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-api-1.0.0.jar",
          "url": "oms-api-1.0.0.jar",
          "size": 59334,
          "sha512": "5dc5452e667b1ca1117dfb867404a0f6ac3fbb5dcf582d00929d2ea899dd450fb08497d6a857089b1b6562ff372ba3688dff8e495a730634271cef4fc981cdc7",
          "sha256": "a17d141e3cc6e7dd8a2dd886f3d83f413b21bdc2703af16c5ccbf790d6270951",
          "sha1": "941b758c6562cff36b2222ec7f3e3a9aa2ea0ea3",
          "md5": "4075533830c909610d741e3d491e99ba"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oms-api-1.0.0-sources.jar",
          "url": "oms-api-1.0.0-sources.jar",
          "size": 25428,
          "sha512": "bdc7a104dffdcf39cfd5876896d6b7a2436f1d8d4b87996a64626f2d725b660e44e680ec40a66fb6c7e7f4d3e563d965d53218fdd6044a856409a1a3e3061ff5",
          "sha256": "109494ac955d532dc23fa6553478f99b68d22a2078f3628f273d857b15653cd3",
          "sha1": "194a6a2742ae732c5f8e7a97b17d0472c4a53c0b",
          "md5": "ff57caf996f0a1926d19a05ca0ea7b87"
        }
      ]
    }
  ]
}
