{
  "formatVersion": "1.1",
  "component": {
    "group": "io.conboi.oms",
    "module": "oms-api",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.4.0"
    }
  },
  "variants": [
    {
      "name": "reobfRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-api-1.0.0.jar",
          "url": "oms-api-1.0.0.jar",
          "size": 58993,
          "sha512": "8c508d452b2664ebeacaef6fcfcac85a4f5041a1ae332fc6de785d083c03c2cabff21025169d95d5693bfade7363444e6ac548c9f6eac2bd5f3fd88ae968cde6",
          "sha256": "1691cbd2614360276c096213dae1643324ca7176494c5047566568a47d3ba971",
          "sha1": "4edd1577487d43ae25799ab8fe7c1b7864588d71",
          "md5": "d1af465ea73e00eb7196f99761ca90ef"
        }
      ]
    },
    {
      "name": "reobfApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "oms-api-1.0.0.jar",
          "url": "oms-api-1.0.0.jar",
          "size": 58993,
          "sha512": "8c508d452b2664ebeacaef6fcfcac85a4f5041a1ae332fc6de785d083c03c2cabff21025169d95d5693bfade7363444e6ac548c9f6eac2bd5f3fd88ae968cde6",
          "sha256": "1691cbd2614360276c096213dae1643324ca7176494c5047566568a47d3ba971",
          "sha1": "4edd1577487d43ae25799ab8fe7c1b7864588d71",
          "md5": "d1af465ea73e00eb7196f99761ca90ef"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "oms-api-1.0.0-sources.jar",
          "url": "oms-api-1.0.0-sources.jar",
          "size": 25129,
          "sha512": "56bb18f8137b06bd38ccc2381529f8ac9104a10f49bd3d586733e820a2d61509cb9ada1f537aed96e1e647393fbd7c91732e9d7a211dc4f97f65094ed50ed9c9",
          "sha256": "4d788e44bd7e54fb9698da4358dc4ec0467d547f1d86a0fc43d5618d7bde3659",
          "sha1": "c5bf86566f0b48f968bcef322a7cf185d11a64d5",
          "md5": "54154f47549e52fb78636fec13422d32"
        }
      ]
    }
  ]
}
