package io.conboi.oms.api.infrastructure.file

import io.conboi.oms.api.extension.ensure
import java.nio.file.Path

/**
 * Manages filesystem paths for a specific OMS addon.
 *
 * [AddonPaths] provides structured, policy-aware access to addon-related
 * directories within the OMS filesystem layout.
 *
 * All paths are created lazily and guaranteed to exist when accessed.
 *
 * @property addonId the unique identifier of the addon
 */
abstract class AddonPaths(
    private val addonId: String
) {

    /**
     * Root directory of the OMS filesystem.
     *
     * This property is initialized during OMS startup.
     */
    lateinit var omsRoot: Path

    /**
     * Root directory of this addon.
     */
    val addonRoot: Path
        get() = omsRoot.ensure(addonId)

    /**
     * Directory for general-purpose addon data.
     */
    val common: Path
        get() = addonRoot.ensure("common")

    /**
     * Directory for addon-generated logs.
     */
    val logs: Path
        get() = addonRoot.ensure("logs")

    /**
     * Directory for cache and temporary data.
     *
     * Contents of this directory may be safely deleted
     * and regenerated by OMS.
     */
    val cache: Path
        get() = addonRoot.ensure("cache")

    /**
     * Returns a filesystem path for a specific feature within this addon.
     *
     * The returned path is created under the directory corresponding
     * to the given [AddonPathType].
     *
     * @param id the unique identifier of the feature
     * @param type the category of path to retrieve
     * @return the filesystem path for the feature
     */
    fun forFeature(
        id: String,
        type: AddonPathType
    ): Path {
        val path = get(type)
        return path.ensure(id)
    }

    /**
     * Returns the root directory corresponding to the given [AddonPathType].
     *
     * @param type the category of path to retrieve
     * @return the corresponding filesystem path
     */
    fun get(type: AddonPathType): Path {
        return when (type) {
            AddonPathType.COMMON -> common
            AddonPathType.LOGS -> logs
            AddonPathType.CACHE -> cache
        }
    }

    /**
     * Initializes the OMS root directory for this addon.
     *
     * This method is invoked by OMS during startup and will be called
     * before any addon paths are accessed.
     *
     * @param omsRootPath the root path of the OMS filesystem
     */
    fun onInitializeOmsRoot(omsRootPath: Path) {
        omsRoot = omsRootPath
    }
}